services:
  - type: web
    name: backend-django
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true # Generate a random secret key
      - key: DEBUG
        value: "0"
      - key: ALLOWED_HOSTS # Set the ALLOWED_HOSTS environment variable
        value: backend-django.onrender.com # Replace with your desired value
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString

databases:
  - name: db
    plan: free
