services:
  - type: web
    name: backend-django
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true # Generate a random secret key
      - key: DEBUG
        value: "0"
      - key: DJANGO_ALLOWED_HOSTS # Set the DJANGO_ALLOWED_HOSTS environment variable
        value: backend-django-oaig.onrender.com .onrender.com localhost 127.0.0.1 # Replace for your deployment URL
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString

databases:
  - name: db
    plan: free
