services:
  - type: web
    name: backend-django
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn BackendTemplate.wsgi:application"
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: BackendTemplate.settings
      - key: SECRET_KEY
        generateValue: true
databases:
  - name: db
    plan: free
